// Declaration compatibility for Emscripten's minimal OpenAL headers.
// EFX is still detected at runtime; these tokens do not enable reverb.
#ifndef DHEWM3_OPENAL_WEB_COMPAT_H
#define DHEWM3_OPENAL_WEB_COMPAT_H

#ifndef AL_APIENTRY
#define AL_APIENTRY
#endif
#ifndef ALC_APIENTRY
#define ALC_APIENTRY
#endif

#ifndef ALC_CONNECTED
#define ALC_CONNECTED 0x313
#endif
#ifndef ALC_EXT_EFX
#define ALC_EXT_EFX 1
#endif
#ifndef ALC_MONO_SOFT
#define ALC_MONO_SOFT 0x1500
#endif
#ifndef ALC_OUTPUT_LIMITER_SOFT
#define ALC_OUTPUT_LIMITER_SOFT 0x199A
#endif
#ifndef ALC_QUAD_SOFT
#define ALC_QUAD_SOFT 0x1503
#endif
#ifndef ALC_STEREO_SOFT
#define ALC_STEREO_SOFT 0x1501
#endif
#ifndef AL_AUXILIARY_SEND_FILTER
#define AL_AUXILIARY_SEND_FILTER 0x20006
#endif
#ifndef AL_DIRECT_FILTER
#define AL_DIRECT_FILTER 0x20005
#endif
#ifndef AL_EAXREVERB_AIR_ABSORPTION_GAINHF
#define AL_EAXREVERB_AIR_ABSORPTION_GAINHF 0x0013
#endif
#ifndef AL_EAXREVERB_DECAY_HFLIMIT
#define AL_EAXREVERB_DECAY_HFLIMIT 0x0017
#endif
#ifndef AL_EAXREVERB_DECAY_HFRATIO
#define AL_EAXREVERB_DECAY_HFRATIO 0x0007
#endif
#ifndef AL_EAXREVERB_DECAY_LFRATIO
#define AL_EAXREVERB_DECAY_LFRATIO 0x0008
#endif
#ifndef AL_EAXREVERB_DECAY_TIME
#define AL_EAXREVERB_DECAY_TIME 0x0006
#endif
#ifndef AL_EAXREVERB_DENSITY
#define AL_EAXREVERB_DENSITY 0x0001
#endif
#ifndef AL_EAXREVERB_DIFFUSION
#define AL_EAXREVERB_DIFFUSION 0x0002
#endif
#ifndef AL_EAXREVERB_ECHO_DEPTH
#define AL_EAXREVERB_ECHO_DEPTH 0x0010
#endif
#ifndef AL_EAXREVERB_ECHO_TIME
#define AL_EAXREVERB_ECHO_TIME 0x000F
#endif
#ifndef AL_EAXREVERB_GAIN
#define AL_EAXREVERB_GAIN 0x0003
#endif
#ifndef AL_EAXREVERB_GAINHF
#define AL_EAXREVERB_GAINHF 0x0004
#endif
#ifndef AL_EAXREVERB_GAINLF
#define AL_EAXREVERB_GAINLF 0x0005
#endif
#ifndef AL_EAXREVERB_HFREFERENCE
#define AL_EAXREVERB_HFREFERENCE 0x0014
#endif
#ifndef AL_EAXREVERB_LATE_REVERB_DELAY
#define AL_EAXREVERB_LATE_REVERB_DELAY 0x000D
#endif
#ifndef AL_EAXREVERB_LATE_REVERB_GAIN
#define AL_EAXREVERB_LATE_REVERB_GAIN 0x000C
#endif
#ifndef AL_EAXREVERB_LATE_REVERB_PAN
#define AL_EAXREVERB_LATE_REVERB_PAN 0x000E
#endif
#ifndef AL_EAXREVERB_LFREFERENCE
#define AL_EAXREVERB_LFREFERENCE 0x0015
#endif
#ifndef AL_EAXREVERB_MODULATION_DEPTH
#define AL_EAXREVERB_MODULATION_DEPTH 0x0012
#endif
#ifndef AL_EAXREVERB_MODULATION_TIME
#define AL_EAXREVERB_MODULATION_TIME 0x0011
#endif
#ifndef AL_EAXREVERB_REFLECTIONS_DELAY
#define AL_EAXREVERB_REFLECTIONS_DELAY 0x000A
#endif
#ifndef AL_EAXREVERB_REFLECTIONS_GAIN
#define AL_EAXREVERB_REFLECTIONS_GAIN 0x0009
#endif
#ifndef AL_EAXREVERB_REFLECTIONS_PAN
#define AL_EAXREVERB_REFLECTIONS_PAN 0x000B
#endif
#ifndef AL_EAXREVERB_ROOM_ROLLOFF_FACTOR
#define AL_EAXREVERB_ROOM_ROLLOFF_FACTOR 0x0016
#endif
#ifndef AL_EFFECTSLOT_EFFECT
#define AL_EFFECTSLOT_EFFECT 0x0001
#endif
#ifndef AL_EFFECTSLOT_GAIN
#define AL_EFFECTSLOT_GAIN 0x0002
#endif
#ifndef AL_EFFECTSLOT_NULL
#define AL_EFFECTSLOT_NULL 0x0000
#endif
#ifndef AL_EFFECT_EAXREVERB
#define AL_EFFECT_EAXREVERB 0x8000
#endif
#ifndef AL_EFFECT_TYPE
#define AL_EFFECT_TYPE 0x8001
#endif
#ifndef AL_FILTER_LOWPASS
#define AL_FILTER_LOWPASS 0x0001
#endif
#ifndef AL_FILTER_NULL
#define AL_FILTER_NULL 0x0000
#endif
#ifndef AL_FILTER_TYPE
#define AL_FILTER_TYPE 0x8001
#endif
#ifndef AL_LOWPASS_GAIN
#define AL_LOWPASS_GAIN 0x0001
#endif
#ifndef AL_LOWPASS_GAINHF
#define AL_LOWPASS_GAINHF 0x0002
#endif


#ifndef AL_EAXREVERB_MAX_AIR_ABSORPTION_GAINHF
#define AL_EAXREVERB_MAX_AIR_ABSORPTION_GAINHF (1.0f)
#endif
#ifndef AL_EAXREVERB_MAX_DECAY_HFLIMIT
#define AL_EAXREVERB_MAX_DECAY_HFLIMIT AL_TRUE
#endif
#ifndef AL_EAXREVERB_MAX_DECAY_HFRATIO
#define AL_EAXREVERB_MAX_DECAY_HFRATIO (2.0f)
#endif
#ifndef AL_EAXREVERB_MAX_DECAY_LFRATIO
#define AL_EAXREVERB_MAX_DECAY_LFRATIO (2.0f)
#endif
#ifndef AL_EAXREVERB_MAX_DECAY_TIME
#define AL_EAXREVERB_MAX_DECAY_TIME (20.0f)
#endif
#ifndef AL_EAXREVERB_MAX_DENSITY
#define AL_EAXREVERB_MAX_DENSITY (1.0f)
#endif
#ifndef AL_EAXREVERB_MAX_DIFFUSION
#define AL_EAXREVERB_MAX_DIFFUSION (1.0f)
#endif
#ifndef AL_EAXREVERB_MAX_ECHO_DEPTH
#define AL_EAXREVERB_MAX_ECHO_DEPTH (1.0f)
#endif
#ifndef AL_EAXREVERB_MAX_ECHO_TIME
#define AL_EAXREVERB_MAX_ECHO_TIME (0.25f)
#endif
#ifndef AL_EAXREVERB_MAX_GAIN
#define AL_EAXREVERB_MAX_GAIN (1.0f)
#endif
#ifndef AL_EAXREVERB_MAX_GAINHF
#define AL_EAXREVERB_MAX_GAINHF (1.0f)
#endif
#ifndef AL_EAXREVERB_MAX_GAINLF
#define AL_EAXREVERB_MAX_GAINLF (1.0f)
#endif
#ifndef AL_EAXREVERB_MAX_HFREFERENCE
#define AL_EAXREVERB_MAX_HFREFERENCE (20000.0f)
#endif
#ifndef AL_EAXREVERB_MAX_LATE_REVERB_DELAY
#define AL_EAXREVERB_MAX_LATE_REVERB_DELAY (0.1f)
#endif
#ifndef AL_EAXREVERB_MAX_LATE_REVERB_GAIN
#define AL_EAXREVERB_MAX_LATE_REVERB_GAIN (10.0f)
#endif
#ifndef AL_EAXREVERB_MAX_LFREFERENCE
#define AL_EAXREVERB_MAX_LFREFERENCE (1000.0f)
#endif
#ifndef AL_EAXREVERB_MAX_MODULATION_DEPTH
#define AL_EAXREVERB_MAX_MODULATION_DEPTH (1.0f)
#endif
#ifndef AL_EAXREVERB_MAX_MODULATION_TIME
#define AL_EAXREVERB_MAX_MODULATION_TIME (4.0f)
#endif
#ifndef AL_EAXREVERB_MAX_REFLECTIONS_DELAY
#define AL_EAXREVERB_MAX_REFLECTIONS_DELAY (0.3f)
#endif
#ifndef AL_EAXREVERB_MAX_REFLECTIONS_GAIN
#define AL_EAXREVERB_MAX_REFLECTIONS_GAIN (3.16f)
#endif
#ifndef AL_EAXREVERB_MAX_ROOM_ROLLOFF_FACTOR
#define AL_EAXREVERB_MAX_ROOM_ROLLOFF_FACTOR (10.0f)
#endif
#ifndef AL_EAXREVERB_MIN_AIR_ABSORPTION_GAINHF
#define AL_EAXREVERB_MIN_AIR_ABSORPTION_GAINHF (0.892f)
#endif
#ifndef AL_EAXREVERB_MIN_DECAY_HFLIMIT
#define AL_EAXREVERB_MIN_DECAY_HFLIMIT AL_FALSE
#endif
#ifndef AL_EAXREVERB_MIN_DECAY_HFRATIO
#define AL_EAXREVERB_MIN_DECAY_HFRATIO (0.1f)
#endif
#ifndef AL_EAXREVERB_MIN_DECAY_LFRATIO
#define AL_EAXREVERB_MIN_DECAY_LFRATIO (0.1f)
#endif
#ifndef AL_EAXREVERB_MIN_DECAY_TIME
#define AL_EAXREVERB_MIN_DECAY_TIME (0.1f)
#endif
#ifndef AL_EAXREVERB_MIN_DENSITY
#define AL_EAXREVERB_MIN_DENSITY (0.0f)
#endif
#ifndef AL_EAXREVERB_MIN_DIFFUSION
#define AL_EAXREVERB_MIN_DIFFUSION (0.0f)
#endif
#ifndef AL_EAXREVERB_MIN_ECHO_DEPTH
#define AL_EAXREVERB_MIN_ECHO_DEPTH (0.0f)
#endif
#ifndef AL_EAXREVERB_MIN_ECHO_TIME
#define AL_EAXREVERB_MIN_ECHO_TIME (0.075f)
#endif
#ifndef AL_EAXREVERB_MIN_GAIN
#define AL_EAXREVERB_MIN_GAIN (0.0f)
#endif
#ifndef AL_EAXREVERB_MIN_GAINHF
#define AL_EAXREVERB_MIN_GAINHF (0.0f)
#endif
#ifndef AL_EAXREVERB_MIN_GAINLF
#define AL_EAXREVERB_MIN_GAINLF (0.0f)
#endif
#ifndef AL_EAXREVERB_MIN_HFREFERENCE
#define AL_EAXREVERB_MIN_HFREFERENCE (1000.0f)
#endif
#ifndef AL_EAXREVERB_MIN_LATE_REVERB_DELAY
#define AL_EAXREVERB_MIN_LATE_REVERB_DELAY (0.0f)
#endif
#ifndef AL_EAXREVERB_MIN_LATE_REVERB_GAIN
#define AL_EAXREVERB_MIN_LATE_REVERB_GAIN (0.0f)
#endif
#ifndef AL_EAXREVERB_MIN_LFREFERENCE
#define AL_EAXREVERB_MIN_LFREFERENCE (20.0f)
#endif
#ifndef AL_EAXREVERB_MIN_MODULATION_DEPTH
#define AL_EAXREVERB_MIN_MODULATION_DEPTH (0.0f)
#endif
#ifndef AL_EAXREVERB_MIN_MODULATION_TIME
#define AL_EAXREVERB_MIN_MODULATION_TIME (0.04f)
#endif
#ifndef AL_EAXREVERB_MIN_REFLECTIONS_DELAY
#define AL_EAXREVERB_MIN_REFLECTIONS_DELAY (0.0f)
#endif
#ifndef AL_EAXREVERB_MIN_REFLECTIONS_GAIN
#define AL_EAXREVERB_MIN_REFLECTIONS_GAIN (0.0f)
#endif
#ifndef AL_EAXREVERB_MIN_ROOM_ROLLOFF_FACTOR
#define AL_EAXREVERB_MIN_ROOM_ROLLOFF_FACTOR (0.0f)
#endif

typedef void (AL_APIENTRY *LPALGENEFFECTS)(ALsizei, ALuint*);
typedef void (AL_APIENTRY *LPALDELETEEFFECTS)(ALsizei, const ALuint*);
typedef ALboolean (AL_APIENTRY *LPALISEFFECT)(ALuint);
typedef void (AL_APIENTRY *LPALEFFECTI)(ALuint, ALenum, ALint);
typedef void (AL_APIENTRY *LPALEFFECTF)(ALuint, ALenum, ALfloat);
typedef void (AL_APIENTRY *LPALEFFECTFV)(ALuint, ALenum, const ALfloat*);
typedef void (AL_APIENTRY *LPALGENFILTERS)(ALsizei, ALuint*);
typedef void (AL_APIENTRY *LPALDELETEFILTERS)(ALsizei, const ALuint*);
typedef ALboolean (AL_APIENTRY *LPALISFILTER)(ALuint);
typedef void (AL_APIENTRY *LPALFILTERI)(ALuint, ALenum, ALint);
typedef void (AL_APIENTRY *LPALFILTERF)(ALuint, ALenum, ALfloat);
typedef void (AL_APIENTRY *LPALGENAUXILIARYEFFECTSLOTS)(ALsizei, ALuint*);
typedef void (AL_APIENTRY *LPALDELETEAUXILIARYEFFECTSLOTS)(ALsizei, const ALuint*);
typedef ALboolean (AL_APIENTRY *LPALISAUXILIARYEFFECTSLOT)(ALuint);
typedef void (AL_APIENTRY *LPALAUXILIARYEFFECTSLOTI)(ALuint, ALenum, ALint);
typedef void (AL_APIENTRY *LPALAUXILIARYEFFECTSLOTF)(ALuint, ALenum, ALfloat);
// The SDK declares HRTF tokens but omits this extension function type.
typedef ALCboolean (ALC_APIENTRY *LPALCRESETDEVICESOFT)(ALCdevice *, const ALCint *);
#endif
